buildscript {
    ext {
        compose_version = '1.10.4'
        wear_compose_version = '1.5.6'
    }
    dependencies {
        classpath 'com.jaredsburrows:gradle-license-plugin:0.9.8'
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.59.2"
    }
}
plugins {
    id 'com.android.application' version '9.0.1' apply false
    id 'org.jetbrains.kotlin.android' version '2.2.20' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.3.10' apply false
    id 'com.google.devtools.ksp' version '2.3.3' apply false
    id 'com.android.library' version '8.13.0' apply false
}