buildscript {
    ext {
        compose_version = '1.8.3'
        wear_compose_version = '1.4.1'
    }
    dependencies {
        classpath 'com.jaredsburrows:gradle-license-plugin:0.9.8'
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.56.2"
    }
}
plugins {
    id 'com.android.application' version '8.8.1' apply false
    id 'org.jetbrains.kotlin.android' version '2.1.20' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.1.20' apply false
    id 'com.google.devtools.ksp' version '2.1.10-1.0.31' apply false
    id 'com.android.library' version '8.9.1' apply false
}